// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case ",[2d$x+2w:oc":
            case "carser city building":return img`
...fbfabbbbbbbbfbaaaaaaaaaaa......c..........................................................................................c......faaaaaaaaaaabfbbbbbbfbafbf..
...fbfabbbbbbbbfbaaaaaaaaaaa......c...........................................d..............................................c......faaaaaaaaaaabfbbbbbfbbafbf..
...fbfabbbbbbbbfbaaaaaaaaaaa......c..........................................................................................c......faaaaaaaaaaabfbbbbfbbbafbf..
...fbfabbbbbbbbfbaaaaaaaaaaa......c..........................................................................................c......faaaaaaaaaaabfbbbbbbbbafbf..
...fbfabbbbbbbbfbaaaaaafffff......c..........................................................................................c......faaaaaaaaaaabfbbbbbbbbafbf..
...fbfabbbbbbbbfbaaaaaabbfbb......f..........................................................................................c......faaaaaaaaaaabfbbbbbbbbafbf..
...fbfabbbbbbbbfbaaaaaabbbbb......c..........................................................................................c......faaaaaaaaaaabfffffffffffbf..
...fbfabbbbbbbbfbaaaaaabbbbb......c..........................................................................................c......faaaaaaaaaaabbbbbbbbbbbbbf..
...fbfabbbbbbbbfbaaaaaafffff......c..........................................................................................c......ffffffffffffcccccccccccccc..
...fbfabbbbbbbbfbaaaaaaaaaaa......c..........................................................................................c......f...........................
...fbfffffffffffbaaaaaaaaaaa......c..........................................................................................c......ffffffffffffcccccccccccccc..
...fbbbbbbbbbbbbbaaaaaaaaaaa......c..........................................................................................c......faaaaaaaaaaabbbbbbbbbbbbbf..
...ccccccccccccccfffffffffff......c..........................................................................................c......faaaaaaaaaaabfffffffffffbf..
..................................c..........................................................................................c......faaaaaaaaaaabfbbbbbbbbafbf..
.....ccccccccccccfffffffffff......c..........................................................................................c......faaaaaaaaaaabfbbbbbbbbafbf..
.....fbbbbbbbbbbbaaaaaaaaaaa......c..........................................................................................c......faaaaaaaaaaabfbbbbbbbbafbf..
.....fbfffffffffbaaaaaaaaaaa......f..........................................................................................c......faaaaaaaaaaabfbbbbfbbbafbf..
.....fbfabbbbbbfbaaaaaaaaaaa......c..........................................................................................c......faaaaaaaaaaabfbbbbbfbbafbf..
.....fbfabbbbbbfbaaaaaaaaaaa......c..........................................................................................c......faaaaaaaaaaabfbbbbbbfbafbf..
.....fbfabbbbbbfbaaaaaaaaaaa......c..........................................................................................c......faaaaaaaaaaabfbbbbbbbbafbf..
.....fbfabbbbbbfbaaaaaaaaaaa......c..........................................................................................c......faaaaaaaaaaabfbbbbbbbbafbf..
.....fbfabbbbbbfbaaaaaaaaaaa......c..........................................................................................c......faaaaaaaaaaabfbbbbbbbbafbf..
.....fbfabbbbbbfbaaaaaaaaffffff...c..........................................................................................c......faaaaaaaaaaabfbbbbbbbbafbf..
.....fbfabbbbbbfbaaaaaaaafbbccc...c..........................................................................................c......ffffffaaaaaabfbbbbbbbbafbf..
.....fbfabbbbbbfbaaaaaaaaffffff...c..........................................................................................c......fbbfbbaaaaaabfbbbbbbbbafbf..
.....fbfabbbbbbfbaaaffffffbbcbc...c..........................................................................................c......fbbbbbaaaaaabfbbbbbbbbafbf..
.....fbfabbbbbbfbaaabbfbbfbbcbc...c..........................................................................................c......fbbbbbaaaaaabfbbbbbbbbafbf..
.....fbfabbbbbbfbaaabbbbbfbbcbc...c..........................................................................................c......ffffffaaaaaabfbbbbbbbbafbf..
.....fbfabbbbbbfbaaabbbbbfbbcbc...c..........................................................................................c......faaaaaaaaaaabfbbbbbbbbafbf..
.....fbfabbbbbbfbaaaffffffbbcbc...c..........................................................................................c......faaaaaaaaaaabfffffffffffbf..
.....fbfabbbbbbfbaaaaaaaaffffff...c..........................................................................................c......faaaaaaaaaaabbbbbbbbbbbbbf..
.....fbfabbbbbbfbaaaaaaaafbbccc...c..........................................................................................c......ffffffffffffcccccccccccccc..
.....fbfffffffffbaaaaaaaaffffff...c..........................................................................................c......f...........................
.....fbbbbbbbbbbbaaaaaaaaaaaf.....c..........................................................................................c......ffffffffffffcccccccccccc....
.....ccccccccccccffffffffffff.....c..........................................................................................c......ffffffffffffcccccccccccc....
............................f.....c..........................................................................................c......faaaaaaaaaaabbbbbbbbbbbf....
...ccccccccccccccffffffffffff.....c..........................................................................................c......faaaaaaaaaaabfffffffffbf....
...fbbbbbbbbbbbbbaaaaaaaaaaaf.....c..........................................................................................c....ffffffaaaaaaaabfbbbbbbafbf....
...fbfffffffffffbaaaaaaaaaaaf.....c..........................................................................................c....cccbbfaaaaaaaabfbbbbbbafbf....
...fbfabbbbbbbbfbaaaaaaaaaaaf.....c..........................................................................................c....ffffffaaaaaaaabfbbbbbbafbf....
...fbfabbbbbbbbfbaaaaaaaaaaaf.....c..........................................................................................c....cbcbbffffffaaabfbbbbbbafbf....
...fbfabbbbbbbbfbaaaaaaaaaaaf.....c..........................................................................................c....cbcbbfbbbbbaaabfbbbbbbafbf....
...fbfabbbfbbbbfbaaaaaaaaaaaf.....c..........................................................................................c....cbcbbfbbbbbaaabfbbbbbbafbf....
...fbfabbfbbbbbfbaaaaaaaaaaaf.....c..........................................................................................c....cbcbbfbbbbbaaabfbbbbbbafbf....
...fbfabfbbbbbbfbaaaaaaaaaaaf.....c..........................................................................................c....cbcbbfbbfbbaaabfbbbbbbafbf....
...fbfabbbbbbbbfbaaaaaaaaaaaf.....c..........................................................................................c....cbcbbffffffaaabfbbbbbbafbf....
...fbfabbbbbbbbfbaaaaaaaaaaaf.....c..........................................................................................f....cbcbbfaaaaaaaabfbbbbbbafbf....
...fbfabbbbbbbbfbaaaaaaaaaaaf.....c..........................................................................................f....ffffffaaaaaaaabfbbbbbbafbf....
...fbfabbbbbbbbfbaaaaaaaaaaaf.....f..........................................................................................c....cccbbfaaaaaaaabfbbbbbbafbf....
...fbfabbbbbbbbfbaaaaaaffffff.....c..........................................................................................c....ffffffaaaaaaaabfbbbbbbafbf....
...fbfabbbbbbbbfbaaaaaabbfbbf.....c..........................................................................................c......faaaaaaaaaaabfbbbbbbafbf....
...fbfabbbbbbbbfbaaaaaabbbbbf.....c..........................................................................................c......faaaaaaaaaaabfbbbbbbafbf....
...fbfabbbbbbbbfbaaaaaabbbbbf.....c..........................................................................................c......faaaaaaaaaaabfbbbbbbafbf....
...fbfabbbbbbbbfbaaaaaaffffff.....c..........................................................................................c......faaaaaaaaaaabfbbbbbbafbf....
...fbfabbbbbbbbfbaaaaaaaaaaaf.....c..........................................................................................c......faaaaaaaaaaabfbbbbbbafbf....
...fbfffffffffffbaaaaaaaaaaaf.....c..........................................................................................c......faaaaaaaaaaabfbbbbbbafbf....
...fbbbbbbbbbbbbbaaaaaaaaaaaf.....c..........................................................................................c......faaaaaaaaaaabfbbbbbbafbf....
...ccccccccccccccffffffffffff.....c..........................................................................................c......faaaaaaaaaaabfffffffffbf....
............................f.....c..........................................................................................c......faaaaaaaaaaabfffffffffbf....
.....ccccccccccccffffffffffff.....c..........................................................................................c......faaaaaaaaaaabbbbbbbbbbbf....
.....fbbbbbbbbbbbaaaaaaaaaaaf.....c..........................................................................................c......ffffffffffffcccccccccccc....
.....fbfffffffffbaaaaaaaaaaaf.....c..........................................................................................c......f...........................
.....fbfffffffffbaaaaaaaaaaaf.....c..........................................................................................c......ffffffffffffcccccccccccccc..
.....fbfabbbbbbfbaaaaaaaaaaaf.....c..........................................................................................c......faaaaaaaaaaabbbbbbbbbbbbbf..
.....fbfabbbbbbfbaaaaaaaaaaaf.....c..........................................................................................c......faaaaaaaaaaabfffffffffffbf..
.....fbfabbbbbbfbaaaaaaaaaaaf.....c..........................................................................................c......faaaaaaaaaaabfbbbbbbbbafbf..
.....fbfabbbbbbfbaaaaaaaaaaaf.....c..........................................................................................c......ffffffaaaaaabfbbbbbbbbafbf..
.....fbfabbbbbbfbaaaaaaaaaaaf.....c..........................................................................................f......fbbbbbaaaaaabfbbbbbbbbafbf..
.....fbfabbbbbbfbaaaaaaaaaaaf.....c..........................................................................................c......fbbbbbaaaaaabfbbbbbbbbafbf..
.....fbfabbbbbbfbaaaaaaaaaaaf.....c..........................................................................................c......fbbfbbaaaaaabfbbbbbbbbafbf..
.....fbfabbbbbbfbaaaaaaaaffffff...c..........................................................................................c......ffffffaaaaaabfbbbbbbbbafbf..
.....fbfabbbbbbfbaaaaaaaafbbccc...c..........................................................................................c......faaaaaaaaaaabfbbbbbbbbafbf..
.....fbfabbbbbbfbaaaaaaaaffffff...c..........................................................................................c......faaaaaaaaaaabfbbbbbbbbafbf..
.....fbfabbbbbbfbaaaaaaaafbbcbc...c..........................................................................................c......faaaaaaaaaaabfbbbbbbbbafbf..
.....fbfabbbbbbfbaaaffffffbbcbc...c..........................................................................................c......faaaaaaaaaaabfbbbbbbbbafbf..
.....fbfabbbbbbfbaaabbfbbfbbcbc...c..........................................................................................c......faaaaaaaaaaabfbbbbbbfbafbf..
.....fbfabbbbbbfbaaabbbbbfbbcbc...c..........................................................................................c......faaaaaaaaaaabfbbbbbfbbafbf..
.....fbfabbbbbbfbaaabbbbbfbbcbc...c..........................................................................................c......faaaaaaaaaaabfbbbbfbbbafbf..
.....fbfabbbbbbfbaaabbbbbfbbcbc...c..........................................................................................c......faaaaaaaaaaabfbbbbbbbbafbf..
.....fbfabbbbbbfbaaaffffffbbcbc...c..........................................................................................c......faaaaaaaaaaabfbbbbbbbbafbf..
.....fbfabbbbbbfbaaaaaaaaffffff...c..........................................................................................c......faaaaaaaaaaabfbbbbbbbbafbf..
.....fbfabbbbbbfbaaaaaaaafbbccc...c..........................................................................................c......faaaaaaaaaaabfffffffffffbf..
.....fbfabbbbbbfbaaaaaaaaffffff...c..........................................................................................c......faaaaaaaaaaabbbbbbbbbbbbbf..
.....fbfffffffffbaaaaaaaaaaaf.....c..........................................................................................c......ffffffffffffcccccccccccccc..
.....fbbbbbbbbbbbaaaaaaaaaaaf.....c..........................................................................................c......f...........................
.....ccccccccccccffffffffffff.....c..........................................................................................c......ffffffffffffcccccccccccc....
.....ccccccccccccffffffffffff.....c..........................................................................................c......faaaaaaaaaaabbbbbbbbbbbf....
............................f.....c..........................................................................................c....ffffffaaaaaaaabfffffffffbf....
...ccccccccccccccffffffffffff.....c..........................................................................................c....cccbbfaaaaaaaabfbbbbbbafbf....
...fbbbbbbbbbbbbbaaaaaaaaaaaf.....c..........................................................................................c....ffffffaaaaaaaabfbbbbbbafbf....
...fbfffffffffffbaaaaaaaaaaaf.....c..........................................................................................c....cbcbbffffffaaabfbbbbbbafbf....
...fbfabbbbbbbbfbaaaaaaaaaaaf.....c..........................................................................................c....cbcbbfbbbbbaaabfbbbbbbafbf....
...fbfabbbbbbbbfbaaaaaaffffff.....c..........................................................................................c....cbcbbfbbbbbaaabfbbbbbbafbf....
...fbfabbbbbbbbfbaaaaaabbbbbf.....c..........................................................................................c....cbcbbfbbfbbaaabfbbbbbbafbf....
...fbfabbbbbbbbfbaaaaaabbbbbf.....c..........................................................................................c....cbcbbffffffaaabfbbbbbbafbf....
...fbfabbbbbbbbfbaaaaaabbfbbf.....c..........................................................................................c....ffffffaaaaaaaabfbbbbbbafbf....
...fbfabbbbbbbbfbaaaaaaffffff.....c..........................................................................................c....cccbbfaaaaaaaabfbbbbbbafbf....
...fbfabbbbbbbbfbaaaaaaaaaaaf.....c..........................................................................................c....ffffffaaaaaaaabfbbbbbbafbf....
...fbfabbbbbbbbfbaaaaaaaaaaaf.....c..........................................................................................c......faaaaaaaaaaabfbbbbbbafbf....
...fbfabbbbbbbbfbaaaaaaaaaaaf.....c..........................................................................................c......faaaaaaaaaaabfbbbbbbafbf....
...fbfabbbbbbbbfbaaaaaaaaaaaf.....c..........................................................................................c......faaaaaaaaaaabfbbbbbbafbf....
...fbfabfbbbbbbfbaaaaaaaaaaaf.....c..........................................................................................c......faaaaaaaaaaabfbbbbbbafbf....
...fbfabbfbbbbbfbaaaaaaaaaaaf.....c..........................................................................................c......faaaaaaaaaaabfbbbbbbafbf....
...fbfabbbfbbbbfbaaaaaaaaaaaf.....c..........................................................................................c......faaaaaaaaaaabfffffffffbf....
...fbfabbbbbbbbfbaaaaaaaaaaaf.....c..........................................................................................c......faaaaaaaaaaabbbbbbbbbbbf....
...fbfabbbbbbbbfbaaaaaaaaaaaf.....c..........................................................................................c......ffffffffffffcccccccccccc....
...fbfabbbbbbbbfbaaaaaaaaaaaf.....c..........................................................................................c......f...........................
...fbfffffffffffbaaaaaaaaaaaf.....c..........................................................................................c......ffffffffffffcccccccccccccc..
...fbbbbbbbbbbbbbaaaaaaaaaaaf.....c..........................................................................................c......faaaaaaaaaaabbbbbbbbbbbbbf..
...ccccccccccccccffffffffffff.....c..........................................................................................c......faaaaaaaaaaabfffffffffffbf..
............................f.....c..........................................................................................c......faaaaaaaaaaabfbbbbbbbbafbf..
...ccccccccccccccffffffffffff.....c..........................................................................................c......ffffffaaaaaabfbbbbbbbbafbf..
...fbbbbbbbbbbbbbaaaaaaaaaaaf.....c..........................................................................................c......fbbbbbaaaaaabfbbbbbbbbafbf..
...fbfffffffffffbaaaaaaaaaaaf.....c..........................................................................................c......fbbbbbaaaaaabfbbbbbbbbafbf..
...fbfabbbbbbbbfbaaaaaaaaaaaf.....c..........................................................................................c......fbbfbbaaaaaabfbbbbbbbbafbf..
...fbfabbbbbbbbfbaaaaaaaaaaaf.....f..........................................................................................c......ffffffaaaaaabfbbbbbbbbafbf..
...fbfabbbbbbbbfbaaaaaaaaaaaf.....c..........................................................................................c......faaaaaaaaaaabfbbbbbbbbafbf..
...fbfabbbfbbbbfbaaaaaaaaaaaf.....c..........................................................................................c......faaaaaaaaaaabfbbbbbbbbafbf..
...fbfabbfbbbbbfbaaaaaaaaaaaf.....c..........................................................................................c......faaaaaaaaaaabfbbbbbbbbafbf..
...fbfabfbbbbbbfbaaaaaaaaaaaf.....c..........................................................................................c......faaaaaaaaaaabfbbbbbbbbafbf..
`;
            case "image2":
            case "carser city road":return img`
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdd111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd1111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb1111dbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbabafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb111ddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd111dbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdd111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd1111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb11111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb11111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb1d1d1bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd1d1dbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbabafccccf.................................
.................................fccccfababbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd11ddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfababbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb1111dbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb11111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb11111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb1111dbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfababbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb111ddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd111dbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdd111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd1111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb11111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb11111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb11111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb1d111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd1d1dbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaafccccf.................................
.................................fccccfaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbabafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd11ddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb1d111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb11111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb1111dbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbabafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb111ddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb1111dbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd1111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb11111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd1111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdd111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd111dbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbabafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb1111dbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb11111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd1d1dbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbabafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd1d1dbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb1dd11bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb11111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb11111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbabafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb1111dbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd111dbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb11111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb1111dbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb11111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd1111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd1111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaafccccf.................................
.................................fccccfaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb11111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb11d11bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdd11dbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbabafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfababbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd1d1dbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdd111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb11111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb1111dbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb111ddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd111dbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdd111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd1111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdd111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd111dbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbabafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb111ddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfababbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb1111dbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb1d111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd1d1dbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfababbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbd11ddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb11dd1bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb11111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbafccccf.................................
.................................fccccfaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb11111bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaafccccf.................................
`;
            case "image4":
            case "carser city building1":return img`
fff5ffffffffffffffffffffffffffbbbbc..........................................................................................cbbbbbbffffffffffffffffffffffffffff
ffffffffff1ffffffffffffffffffbfbbbc...........................................d..............................................cbbbbffffffffffffff111ffffffffff1ff
f1fffffffffffffffffffffffffffbbfbbc..........................................................................................cbbbfbbfff1f1ffffffffffff1fff1fffff
f5fff1ffffff1f1ffffffffffffffbbbfbc..........................................................................................cbffbbbffffffff1ffff1ffffffff1fffff
fff1ffff1ffffffffffff1ff1ffffbbbbfc..........................................................................................cfbbbbbfffffffffffffffffffffffff5ff
f1fffffff1fffffffffffffffffffbbbbbf..........................................................................................cbbbbbbfffff1fffffffffffff1ffff1fff
ffff1fffffffff5fff1ffffffffffbbbbbc..........................................................................................cbbbbbbfffffffffffff1ffffffffffffff
ffffffffffffff1ffffffff1fffffbbbbbc..........................................................................................cbbbbbbfff1fffff1ffffffffffffff1fff
f1ffff1fff5ffffffffffffffffffbbbbbc..........................................................................................cbbbbbbfffffffffffffffff1ffff1fffff
fffffffff1ffffff1fff1ffffffffbbbbbc..........................................................................................cbbbbbbfffff1ffffffffffffffff1fffff
f5fffffffffffffffffffff1fffffbbbbbc..........................................................................................cbbbbbbff1fffffffffffffffffffffffff
fff1ff1ffffffffffffff5ffffffffbbbbc..........................................................................................cbbbbbbfffff1ffff1ffff1ffffffffffff
fffff5fffffffff1fffffffffffffbfbbbc..........................................................................................cbbbbbfffffffffffffffffffffff1ff51f
fffffffffff1fffffffffff1fffffbbfbbc..........................................................................................cbbbbfbffffffffffffffffffffffffffff
f1fffffff5fffffffffffffffffffbbbfbc..........................................................................................cbbbfbbfff1f1ff1fffffff5fffffffffff
f5fff1ffffffffffffff1ffffffffbbbbfc..........................................................................................cbbbfbbfff1fffffffffffffffffffff1ff
fff1fffffffffffffffffffffffffbbbbbf..........................................................................................cbbfbbbfffffffffffffff1fff1ffffffff
fffffffff1ff1ff1ffffff15fffffbbbbbc..........................................................................................cbfbbbbfffffffff1ffffffffffffffffff
ffffff1ffffffffffffffffffffffbbbbbc..........................................................................................cbfbbbbffffffffffffffffffffffffff1f
ffffffffffffffffffffff1ffffffbbbbbc..........................................................................................cfbbbbbffff1ffffffffffffffffff5ffff
ff5fffffffff1ffffffffffffffffbbbbbc..........................................................................................cbbbbbbfffffffffffffffff1ffffffff1f
fffff1fff1fffffffffffffffffffbbbbbc..........................................................................................cbbbbbbfff1fffff5fff1ffffffffffff1f
ff1ffffffffffff1fff1fffffffffbbbbbc..........................................................................................cbbbbbbfff1ffffffffffffffff5fffffff
fffffffffffffffffffff1fffffffbbbbbc..........................................................................................cbbbbbbffff1fff1fffffffffffffff1fff
ff1fffffffffffffffff5ffffffffbbbbbc..........................................................................................cbbbbbbffffffffffffffffffffffffff5f
ffffff1f5ffffffffffffffffffffbbbbbc..........................................................................................cbbbbbbffff1ffffffffff1ffffffffff1f
ff51fffff1ff1ffffffff1f1fffffbbbbbc..........................................................................................cbbbbbbfffffffffffffffff1fffff1ffff
fffffffffffffffffffffffffffffbbbbbc..........................................................................................cbbbbbbffffffffffffffffffffffffffff
ffffffffff5fffffff1ffffffffffbbfbbc..........................................................................................cbbbbbbffff1fffffffffffffffffffffff
ff1f1fff1f1ff1fffffffffffffffbbfbbc..........................................................................................cbbbbbbffffffffffffffffffffffff1fff
fffffffffffffffffffffffffffffbbbfbc..........................................................................................cbbbbbbfff1fffffff1ffffffffffffffff
ff1ffffffffffffff1ff1fff1ffffbbbbfc..........................................................................................cbbbbbbffffffff1ff5ffffffffffffff1f
fffff1ffff1ff1ffffff1fff1ffffbbbbbc..........................................................................................cbbbbbbffffffffffffffff5fffffffffff
fffffffffffffffffffffffffffffbbbbbc..........................................................................................cbbbbbbffffffffffffff1fffffffffffff
fffffffffffffffffff1fffffffffbbbbbc..........................................................................................cbbbbbbfff1ffffff1fffffffffff1fffff
ffffffffffffff1f1ffffffffffffbbbbbc..........................................................................................cbbbbbbfffffffffff1ffffffffffffffff
f515ff1fff1ffffffffffffffffffbbbbbc..........................................................................................cbbbbbffffffffffffffffff1fffffff1ff
ff1ff1fffffffffff1fffffffffffbbbbbc..........................................................................................cbbbbfbff1fffffffffffffffffffffffff
fffffffffffff1f1fffffffffffffbbbbbc..........................................................................................cbbbfbbfffff1ffffffffffffffff5fffff
fffffffffffffffffffffffffffffbbbbbc..........................................................................................cbbfbbbffffffffffffffffffffffffffff
ffffffff1ffffffff1ff15fffffffbbbbbc..........................................................................................cbbfbbbff1ffffffffff55ffffffff1ffff
ffffffff1ffff1ffffffffff1ffffbbbbbc..........................................................................................cbfbbbbfffffffffffffff1ffff1fffffff
f1fffffffff5fffffffffffffffffbbbbbc..........................................................................................cbfbbbbfffffffffff1ffffffffffffffff
fffff1ffffffff1ff1ffffffffffffbbbbc..........................................................................................cfbbbbbffffffffffffffffffffffffff1f
fffffffffff1fffffffff1fff1fffbfbbbc..........................................................................................cfbbbbbffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbfbbc..........................................................................................cfbbbbbfff1ffffffffffffffffff1fffff
f51fffffffffff1ffffffffffffffbbbfbc..........................................................................................fbbbbbbffffffffffffffffffffffffffff
ff1ffff1fffffffffffffffff1fffbbbbfc..........................................................................................fbbbbbbffffffffffffffffffffffffffff
f1ff1fffffff5ffff1fffffffffffbbbbbf..........................................................................................cbbbbbbffffffffffffffff1ffffffff1ff
f1ffff1fffffffffff1ffffffffffbbbbbc..........................................................................................cbbbbbbffff1ff1f1fffffffffff1ffffff
fffffffffffff1ffffffff1ffffffbbbbbc..........................................................................................cbbbbbbfffffffff5ffffffffff5fffff5f
fff15ffffffffffffffffffffffffbbbbbc..........................................................................................cbbbbbbfffff1fffffffffffffffff1ffff
f5fffffff1fffff5ffff5ffffffffbbbbbc..........................................................................................cbbbbbbffffffffffffffffffffffffffff
f1ffffff1fffffffffffffffff1ffbbbbbc..........................................................................................cbbbbbbffffffffffff1fffff1fffffffff
fffffffffffffffffffffffffffffbbbbbc..........................................................................................cbbbbbbffffffff1fff1fffffffffffffff
ffff5ffffff1fff1fff1fffff1fffbbbbbc..........................................................................................cbbbbbbffffffffffffffffffffffffff1f
fffffffffffffffffffffffffffffbbbbbc..........................................................................................cbbbbbbffffffffff5ffffff5ffff1fffff
fffffff1fff1fffffffffffffffffbbbbbc..........................................................................................cbbbbbbffffffffffffffff1fffffffff5f
f1fff1ffffff1ffffffffffffffffbbbbbc..........................................................................................cbbbbbbffff1fffffffffffff5fffffffff
fff5ffffffffffffffff1ff1fffffbbbbbc..........................................................................................cbbbbbfffffffffffffffffffffffffffff
ffffffff1fffffff1ffffffffffffbbbbbc..........................................................................................cbbbbfbffffffffffff1fffffff1fffffff
fff1fffffffffffffffffffffffffbbbbbc..........................................................................................cbbbfbbfffff1ff1fffffffffffffffffff
ffffffffff5fffffffffffff1fffffbbbbc..........................................................................................cbbbfbbffffffffffffffff1ffffff1ffff
ffffffffffff1ffffffffffffffffbfbbbc..........................................................................................cbbfbbbfffffffffffffffff1fff1ffffff
ffffff1ffff5ffffff5ffffffffffbfbbbc..........................................................................................cbfbbbbffffffffffffffffffffffffffff
ff1ffffffffffffffffffffffffffbbfbbc..........................................................................................cfbbbbbfff1fffff1fff1fff1ffffff5fff
ffffffffffffffff1fff1ffffffffbbbfbc..........................................................................................cfbbbbbffffffffffffffffffffffffffff
ffffffffff1fffff1ffffffffffffbbbbfc..........................................................................................fbbbbbbff1fffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbbbc..........................................................................................cbbbbbbffffffff5ffff5ffffffffffffff
ff1ff1fffffffffffffffff1fffffbbbbbc..........................................................................................cbbbbbbffffffffffffffffffffffff51ff
ffffffff5ffffffffff5fffffffffbbbbbc..........................................................................................cbbbbbbffffff1ffffffff1ffffffffffff
fffffff1fffffffffff1f1ff1ffffbbbbbc..........................................................................................cbbbbbbffffffffff1fffffffffffffffff
fff1ffffffff1ffffffffffffffffbbbbbc..........................................................................................cbbbbbbfffffffffff1ffff5fffffffffff
f1fffffffffffffffffffffffffffbbbbbc..........................................................................................cbbbbbbfff1fffffffffffffffff1ffffff
fffffffffffffffffffffffffffffbbbbbc..........................................................................................cbbbbbbffffffffffffff1fffffffffffff
ffffff1ffffffffffffffffff1fffbbbbbc..........................................................................................cbbbbbbffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbbbbbc..........................................................................................cbbbbbbfff1fff1fffffffff1ffffffffff
ff1fffffffffffffffffffffffffffbbbbc..........................................................................................cbbbbbbfffffffffff1ff1ffffffff1ffff
fffffffffffffffff1fffffffffffbffbbc..........................................................................................cbbbbbbfffffffffffffffff5fffffffff1
ffffffff1ffff1fffffffffffffffbbfbbc..........................................................................................cbbbbbfffff1ffffffffff1ffff1fffffff
fffff1ffffffff55ffffffffff1ffbbbfbc..........................................................................................cbbbbfbfffffff51ff1ffffffff1fffffff
f1fffffffffffffffffffffffffffbbbbfc..........................................................................................cbbbbfbffffffffffffffffffffffffffff
ffffff5ffffffffffffffff1fffffbbbbbc..........................................................................................cbbbfbbfffffffffffff1f1ffffffffffff
ffffffffffffffffffffffffff1ffbbbbbc..........................................................................................cbbfbbbfffffffffff1fffffffffff1ff1f
fff1fffffff1fffffffffffffffffbbbbbc..........................................................................................cbfbbbbffffffffffffffffff1fff1ff51f
ff1ffffffffffffff1fffffffffffbbbbbc..........................................................................................cbfbbbbffffffffffff1f1fffffffffffff
ffffff1fffffffffff1ffffff1fffbbbbbc..........................................................................................cfbbbbbfffffffff1ffffffffffffffffff
ffffffffffffff1ffffffffffffffbbbbbc..........................................................................................cbbbbbbffffffffffffffffffffffffffff
ffffffffffff5ffffffffffffffffbbbbbc..........................................................................................cbbbbbbffff1fff1ffffff1ff1ffff1ffff
f1fffffffffffffff5ff1ffffffffbbbbbc..........................................................................................cbbbbbbffff1fff1ff1ffffffffffffff1f
fffffffffffffffff1fffffff1fffbbbbbc..........................................................................................cbbbbbbffffffffffffffffffffffffffff
ffff1ffffffffffffffffffffffffbbbbbc..........................................................................................cbbbbbbfffffffffffffff1ff1f1fff1f1f
ffffffffffffffffffffffff1ffffbbbbbc..........................................................................................cbbbbbbffffffffff1fffffff5fffffffff
fffffffffffffffffffffffffffffbbbbbc..........................................................................................cbbbbbbffffffffffffffffffffffffffff
f15ff1fffff1ffffffffffffffffffbbbbc..........................................................................................cbbbbbbfffff1f1ffffffff1ff1fffff1ff
fffffffffffff1ffffffffff1ffffbfbbbc..........................................................................................cbbbbbbffffffffffffffffffff5f1fffff
fffffffffffffffffffffffffffffbbfbbc..........................................................................................cbbbbbbffffffff5fffffffffffffffff1f
ffff1fffffffffffffff1fff1ffffbbbfbc..........................................................................................cbbbbbbfffffff1ffffffffffffffffffff
ffffffff5ffffffffffffffffffffbbbbfc..........................................................................................cbbbbbffffffffff1fff1ffffffffffff1f
fffffffffffffff1fff5fffffffffbbbbbc..........................................................................................cbbbffbfffffffffffffffffff1fff1ffff
fffffffffffffffffffffffffffffbbbbbc..........................................................................................cbbfbbbffffffffffffffff1fffffffff1f
fffff5ffffffffffffffffff1ffffbbbbbc..........................................................................................cbfbbbbffffff1fffffffffffffffffffff
fffffffffffffffffffffffffffffbbbbbc..........................................................................................cfbbbbbffffffffffffffffffffff1fffff
fffffffffffffffffffffffffffffbbbbbc..........................................................................................cbbbbbbfffff51ffffff1ff1ff1ffffffff
fffffffff1fff1ffffffffffff1ffbbbbbc..........................................................................................cbbbbbbfffffffffffffffffffffffff1ff
fff1ff1ffffffffffffffffffffffbbbbbc..........................................................................................cbbbbbbffffffff1ffffffffffffff1ffff
ff5fffffffff5fffffff1ff1fffffbbbbbc..........................................................................................cbbbbbbfffffffffffffffffff5ffffffff
ffffffffffffffffffffffffff1ffbbbbbc..........................................................................................cbbbbbbfffff1fffffffffff1ffffffffff
ffffff1ffffffffffffffffffffffbbbbbc..........................................................................................cbbbbbbfffffffffffff1fffffffff5ffff
fffffffffffff1ffff1ffff1fffffbbbbbc..........................................................................................cbbbbbbfffffff5ffffffffffffff1ff1ff
fffffffffffffffffffffffffffffbbbbbc..........................................................................................cbbbbbbfffff1ffffffffffffffffffffff
ffffff1ffffffffffffffff1f1ffffbbbbc..........................................................................................cbbbbbbffffffff1fff1ffffff1fffff5ff
ffffff1ffff1fffffffffffffffffbfbbbc..........................................................................................cbbbbbfffffffffffffffffff5fff1fffff
ff1ffffffffffffffff1fffffffffbbfbbc..........................................................................................cbbbffbfffff1ffffffff1fffffffffffff
fffff1fffffffff1fffffffffffffbbbffc..........................................................................................cbbfbbbffffffffff1fff5fffffffff1fff
fff5fffff1fff1fffffffff1fffffbbbbbf..........................................................................................cbfbbbbfffffffffffffffffff1ffffffff
fffffffffffffffffffffffffffffbbbbbc..........................................................................................cfbbbbbffff1ff1ffffffffffff1fffffff
ffff1ffffffffffffffffffffffffbbbbbc..........................................................................................cbbbbbbffffffffffffff1f1fffffffffff
ffffffff1ff1ffffff1ff1fffffffbbbbbc..........................................................................................cbbbbbbffffffffffffffffffffffffffff
ffffffffffffffff1ffffffff1fffbbbbbc..........................................................................................cbbbbbbffffffffffffffffffffffffffff
`;
            case "image1":
            case "carser city building0":return img`
............................ffbbbbc..........................................................................................cbbbbbbf...........................
............................fbfbbbc...........................................d..............................................cbbbbfff...........................
............................fbbfbbc..........................................................................................cbbbfbbf...........................
............................fbbbfbc..........................................................................................cbffbbbf...........................
............................fbbbbfc..........................................................................................cfbbbbbf...........................
............................fbbbbbf..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................ffbbbbc..........................................................................................cbbbbbbf...........................
............................fbfbbbc..........................................................................................cbbbbbff...........................
............................fbbfbbc..........................................................................................cbbbbfbf...........................
............................fbbbfbc..........................................................................................cbbbfbbf...........................
............................fbbbbfc..........................................................................................cbbbfbbf...........................
............................fbbbbbf..........................................................................................cbbfbbbf...........................
............................fbbbbbc..........................................................................................cbfbbbbf...........................
............................fbbbbbc..........................................................................................cbfbbbbf...........................
............................fbbbbbc..........................................................................................cfbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbfbbc..........................................................................................cbbbbbbf...........................
............................fbbfbbc..........................................................................................cbbbbbbf...........................
............................fbbbfbc..........................................................................................cbbbbbbf...........................
............................fbbbbfc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbff...........................
............................fbbbbbc..........................................................................................cbbbbfbf...........................
............................fbbbbbc..........................................................................................cbbbfbbf...........................
............................fbbbbbc..........................................................................................cbbfbbbf...........................
............................fbbbbbc..........................................................................................cbbfbbbf...........................
............................fbbbbbc..........................................................................................cbfbbbbf...........................
............................fbbbbbc..........................................................................................cbfbbbbf...........................
............................ffbbbbc..........................................................................................cfbbbbbf...........................
............................fbfbbbc..........................................................................................cfbbbbbf...........................
............................fbbfbbc..........................................................................................cfbbbbbf...........................
............................fbbbfbc..........................................................................................fbbbbbbf...........................
............................fbbbbfc..........................................................................................fbbbbbbf...........................
............................fbbbbbf..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbff...........................
............................fbbbbbc..........................................................................................cbbbbfbf...........................
............................fbbbbbc..........................................................................................cbbbfbbf...........................
............................ffbbbbc..........................................................................................cbbbfbbf...........................
............................fbfbbbc..........................................................................................cbbfbbbf...........................
............................fbfbbbc..........................................................................................cbfbbbbf...........................
............................fbbfbbc..........................................................................................cfbbbbbf...........................
............................fbbbfbc..........................................................................................cfbbbbbf...........................
............................fbbbbfc..........................................................................................fbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................ffbbbbc..........................................................................................cbbbbbbf...........................
............................fbffbbc..........................................................................................cbbbbbbf...........................
............................fbbfbbc..........................................................................................cbbbbbff...........................
............................fbbbfbc..........................................................................................cbbbbfbf...........................
............................fbbbbfc..........................................................................................cbbbbfbf...........................
............................fbbbbbc..........................................................................................cbbbfbbf...........................
............................fbbbbbc..........................................................................................cbbfbbbf...........................
............................fbbbbbc..........................................................................................cbfbbbbf...........................
............................fbbbbbc..........................................................................................cbfbbbbf...........................
............................fbbbbbc..........................................................................................cfbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................ffbbbbc..........................................................................................cbbbbbbf...........................
............................fbfbbbc..........................................................................................cbbbbbbf...........................
............................fbbfbbc..........................................................................................cbbbbbbf...........................
............................fbbbfbc..........................................................................................cbbbbbbf...........................
............................fbbbbfc..........................................................................................cbbbbbff...........................
............................fbbbbbc..........................................................................................cbbbffbf...........................
............................fbbbbbc..........................................................................................cbbfbbbf...........................
............................fbbbbbc..........................................................................................cbfbbbbf...........................
............................fbbbbbc..........................................................................................cfbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................ffbbbbc..........................................................................................cbbbbbbf...........................
............................fbfbbbc..........................................................................................cbbbbbff...........................
............................fbbfbbc..........................................................................................cbbbffbf...........................
............................fbbbffc..........................................................................................cbbfbbbf...........................
............................fbbbbbf..........................................................................................cbfbbbbf...........................
............................fbbbbbc..........................................................................................cfbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
............................fbbbbbc..........................................................................................cbbbbbbf...........................
`;
            case "yQ17||2serX3;RdHI":
            case "decker":return img`
. f f f . . . . . . f f f . 
f c 8 c f . . . . f c 8 c f 
f c 8 c f . . . . f c 8 c f 
. f 8 f . . . . . . f 8 f . 
. f 8 f . . . . . . f 8 f . 
. f 8 f . f f f f . f 8 f . 
. f 8 f f 1 c c c f f 8 f . 
. f 8 8 8 c 1 c 1 8 8 8 f . 
. f c 8 c c 1 c c 1 8 c f . 
. f c 8 c c c 1 c c 8 c f . 
. f c 8 c c c c 1 c 8 c f . 
. f 8 e 2 e b b 4 5 4 8 f . 
. f 8 2 e 2 b b 5 4 5 8 f . 
. f 8 8 8 8 8 8 8 8 8 8 f . 
. f 8 8 8 8 8 8 8 8 8 8 f . 
. f c 8 c c c c c c 8 c f . 
. f 8 c 8 8 8 8 8 8 c 8 f . 
. f 8 8 c 8 8 8 8 c 8 8 f . 
. f 4 5 c 8 8 8 8 c 5 4 f . 
. . f 4 c 8 8 8 8 c 4 f . . 
. . . f f f f f f f f . . . 
`;
            case "image3":
            case "road block":return img`
. . f f f . . . . . . f f f . . 
. f 5 4 1 f . . . . f 5 4 1 f . 
. f 4 5 4 f . . . . f 4 5 4 f . 
. f 1 4 5 f . . . . f 1 4 5 f . 
. . f f f . . . . . . f f f . . 
f f f f f f f f f f f f f f f f 
f 4 1 1 1 1 4 1 1 4 1 1 1 1 4 f 
f f f f f f f f f f f f f f f f 
. f c f . . . . . . . . f c f . 
f f f f f f f f f f f f f f f f 
f 4 1 1 1 1 4 1 1 4 1 1 1 1 4 f 
f f f f f f f f f f f f f f f f 
. f c f . . . . . . . . f c f . 
. f c f . . . . . . . . f c f . 
. f c f f f f f f f f f f c f . 
. f c f . . . . . . . . f c f . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
